[tool.poetry]
name = "openweathermap-productizer-v1"
version = "1.0.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.6"
fastapi = {version = "^0.47.1"}
uvicorn = "^0.11.2"
ujson = "^1.35"
aiohttp = "^3.6.2"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
